"""
Generates the roadmap workbooks.

  python3 templates/make_templates.py                       # from the sample data (examples)
  python3 templates/make_templates.py "Enterprise Setup.xlsx"  # blank product templates for every area in your setup workbook

Outputs:
  templates/Enterprise Setup.xlsx          themes, KPIs, product areas, settings (Director owns)
  templates/Roadmap - TEMPLATE.xlsx        blank product-area roadmap with one example row
  templates/Roadmap - <CODE>.xlsx          one blank roadmap per product area (when a setup workbook is given)
  examples/roadmaps/*.xlsx                 sample setup + filled product roadmaps (sample mode only)
Requires: pip install openpyxl
"""
import json, sys, datetime as dt
from pathlib import Path
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule
from openpyxl.comments import Comment

ROOT = Path(__file__).resolve().parent.parent
FONT = 'Arial'
INK, MUTED = '1F2933', '5A6574'
HEAD_FILL = PatternFill('solid', fgColor='1F3A4D')
INPUT_FILL = PatternFill('solid', fgColor='FFF7D6')
EX_FILL = PatternFill('solid', fgColor='F1F3F5')
THIN = Side(style='thin', color='D5DBE1')
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
ROWS = 200  # pre-formatted input rows

HORIZONS = [('Commit', 'Scope and dates are firm. We track against them.'),
            ('Plan', 'Direction is set. Dates are indicative.'),
            ('Explore', 'Options under evaluation, not commitments.')]
STATUSES = [('Not started', 'Work has not begun.'), ('On track', 'Expected to finish by the end date.'),
            ('At risk', 'Could miss the end date without action. Add a risk note.'),
            ('Off track', 'Will miss the end date. Add a risk note with the recovery plan.'), ('Done', 'Finished.')]
TYPES = [('Release', 'Something ships or goes live.'), ('Pilot', 'Limited rollout to test with users.'),
         ('Review gate', 'Leadership checks outcome impact. Shows on the Outcomes view.'),
         ('Decision', 'A go/no-go or direction decision.')]


def f(bold=False, color=INK, size=10, italic=False):
    return Font(name=FONT, bold=bold, color=color, size=size, italic=italic)


def header(ws, cols, row=1):
    for c, (name, width) in enumerate(cols, 1):
        cell = ws.cell(row=row, column=c, value=name)
        cell.font = f(True, 'FFFFFF'); cell.fill = HEAD_FILL; cell.border = BOX
        cell.alignment = Alignment(vertical='center', wrap_text=True)
        ws.column_dimensions[cell.column_letter].width = width
    ws.row_dimensions[row].height = 30


def body(ws, first, last, ncols, date_cols=(), wrap_cols=()):
    for r in range(first, last + 1):
        for c in range(1, ncols + 1):
            cell = ws.cell(row=r, column=c)
            cell.font = f(); cell.border = BOX
            cell.alignment = Alignment(vertical='top', wrap_text=c in wrap_cols)
            if c in date_cols: cell.number_format = 'm/d/yyyy'


def dv_list(ws, formula, rng, prompt=None, title=None):
    dv = DataValidation(type='list', formula1=formula, allow_blank=True, showErrorMessage=True,
                        errorTitle='Pick from the list', error='Choose a value from the dropdown.')
    if prompt: dv.promptTitle, dv.prompt, dv.showInputMessage = title or 'Tip', prompt, True
    ws.add_data_validation(dv); dv.add(rng)


def dv_date(ws, rng):
    dv = DataValidation(type='date', operator='between', formula1='DATE(2020,1,1)', formula2='DATE(2040,12,31)',
                        allow_blank=True, showErrorMessage=True, errorTitle='Date needed', error='Enter a date, e.g. 10/1/2026.')
    ws.add_data_validation(dv); dv.add(rng)


def d(s):
    return dt.datetime.strptime(s, '%Y-%m-%d') if s else None


# ---------------------------------------------------------------- enterprise setup
def make_enterprise(path, settings, themes, areas):
    wb = Workbook()
    ws = wb.active; ws.title = 'Instructions'
    ws.column_dimensions['A'].width = 100
    lines = [('Enterprise roadmap setup', f(True, size=16)),
             ('Owned by the Director of Enterprise Modernization. Delivery managers do not edit this file.', f(color=MUTED)),
             ('', f()),
             ('Settings: organization name, fiscal year start month (1 = January, 10 = October for US federal FY), Jira link.', f()),
             ('Themes: the enterprise strategic themes and the KPI each one moves. Review quarterly.', f()),
             ('Product Areas: one row per product area. The Code (e.g. CLD) is used in initiative IDs and in each product roadmap file.', f()),
             ('', f()),
             ('Yellow cells are the ones to edit. After changing themes or product areas, regenerate the product templates', f()),
             ('(python3 templates/make_templates.py "Enterprise Setup.xlsx") so their dropdowns match.', f())]
    for i, (t, ft) in enumerate(lines, 1):
        ws.cell(row=i, column=1, value=t).font = ft

    s = wb.create_sheet('Settings')
    s.column_dimensions['A'].width = 28; s.column_dimensions['B'].width = 44; s.column_dimensions['C'].width = 60
    rows = [('Organization', settings.get('orgName', ''), 'Shown in the dashboard header.'),
            ('Fiscal year start month', settings.get('fiscalYearStartMonth', 1), '1 = calendar year, 10 = US federal fiscal year.'),
            ('Jira base URL', settings.get('jiraBaseUrl', ''), 'e.g. https://samtek.atlassian.net. Used to link Jira epics.')]
    for r, (k, v, note) in enumerate(rows, 1):
        s.cell(row=r, column=1, value=k).font = f(True)
        c = s.cell(row=r, column=2, value=v); c.font = f(); c.fill = INPUT_FILL; c.border = BOX
        s.cell(row=r, column=3, value=note).font = f(color=MUTED)

    t = wb.create_sheet('Themes')
    cols = [('Code', 9), ('Theme', 32), ('Description', 44), ('KPI', 30), ('KPI unit', 10), ('Baseline', 10), ('Current', 10), ('Target', 10)]
    header(t, cols); body(t, 2, 21, len(cols), wrap_cols=(3,))
    for r, th in enumerate(themes, 2):
        k = th.get('kpi') or {}
        for c, v in enumerate([th['id'], th['name'], th.get('description', ''), k.get('name', ''), k.get('unit', ''),
                               k.get('baseline'), k.get('current'), k.get('target')], 1):
            t.cell(row=r, column=c, value=v)
    for r in range(2, 22):
        for c in range(1, len(cols) + 1): t.cell(row=r, column=c).fill = INPUT_FILL
    t.freeze_panes = 'A2'
    t.cell(row=1, column=7).comment = Comment('Update Current each quarter from your KPI source.', 'Roadmap')

    a = wb.create_sheet('Product Areas')
    cols = [('Code', 9), ('Product area', 28), ('Product owner', 22), ('Delivery manager', 22), ('Description', 50), ('Active', 9)]
    header(a, cols); body(a, 2, 31, len(cols), wrap_cols=(5,))
    for r, ar in enumerate(areas, 2):
        for c, v in enumerate([ar['id'], ar['name'], ar.get('owner', ''), ar.get('deliveryManager', ''), ar.get('description', ''), 'Yes'], 1):
            a.cell(row=r, column=c, value=v)
    for r in range(2, 32):
        for c in range(1, len(cols) + 1): a.cell(row=r, column=c).fill = INPUT_FILL
    dv_list(a, '"Yes,No"', 'F2:F31')
    a.freeze_panes = 'A2'
    wb.save(path)


def read_enterprise(path):
    wb = load_workbook(path, data_only=True)
    def rows(name):
        ws = wb[name]; hdr = [str(c.value or '').strip() for c in ws[1]]
        return [dict(zip(hdr, [c.value for c in r])) for r in ws.iter_rows(min_row=2) if any(c.value not in (None, '') for c in r)]
    s = {str(r[0].value).strip(): r[1].value for r in wb['Settings'].iter_rows() if r[0].value}
    settings = {'orgName': s.get('Organization', ''), 'fiscalYearStartMonth': s.get('Fiscal year start month', 1), 'jiraBaseUrl': s.get('Jira base URL', '')}
    themes = [{'id': r['Code'], 'name': r['Theme'], 'description': r.get('Description') or ''} for r in rows('Themes') if r.get('Theme')]
    areas = [{'id': r['Code'], 'name': r['Product area'], 'deliveryManager': r.get('Delivery manager') or ''}
             for r in rows('Product Areas') if r.get('Product area') and str(r.get('Active') or 'Yes').lower() != 'no']
    return settings, themes, areas


# ---------------------------------------------------------------- product roadmap
INIT_COLS = [('ID', 10), ('Product area', 12), ('Initiative', 34), ('Strategic theme', 28), ('Horizon', 11), ('Status', 12), ('Start date', 12),
             ('End date', 12), ('Owner', 18), ('Summary', 46), ('Jira epic', 12), ('Depends on', 16), ('Risk note', 40), ('Last reviewed', 13), ('Notes (not shown on dashboard)', 48)]
MS_COLS = [('Initiative ID', 13), ('Milestone', 36), ('Date', 12), ('Type', 13), ('Done', 8), ('Jira epic', 12)]


def make_product(path, area, themes, areas, initiatives=(), milestones=(), example=False, updated_by=''):
    wb = Workbook()
    code = area['id'] if area else ''

    # Instructions
    ws = wb.active; ws.title = 'Instructions'
    ws.column_dimensions['A'].width = 24; ws.column_dimensions['B'].width = 70; ws.column_dimensions['C'].width = 26
    ws['A1'] = f"{area['name']} roadmap" if area and area.get('name') else 'Product area roadmap'; ws['A1'].font = f(True, size=16)
    ws['A2'] = 'Maintained by the delivery manager. Update monthly, and at least every quarter.'; ws['A2'].font = f(color=MUTED)
    steps = ['On the Product Area tab, pick your product area code (cell B1, e.g. AZC) and put your name and today\'s date. In a combined file that covers several areas, leave B1 blank and set Product area on each initiative row.',
             'On the Initiatives tab, add or update one row per initiative. Use the dropdowns.',
             'Every time you look at a row, set Last reviewed to today, even if nothing changed.',
             'If an initiative is At risk or Off track, write a Risk note: what is wrong and what you are doing about it.',
             'On the Milestones tab, add 1-3 milestones per committed initiative. Add a Review gate where leadership should check impact.',
             'Preview: drag this file onto the roadmap dashboard ("Preview a roadmap file"). Fix anything in the Data quality tab.',
             'Save the file in the shared roadmap folder by the monthly cutoff.']
    ws['A4'] = 'How to update'; ws['A4'].font = f(True, size=12)
    for i, s_ in enumerate(steps, 5):
        ws.cell(row=i, column=1, value=f'Step {i - 4}').font = f(True)
        c = ws.cell(row=i, column=2, value=s_); c.font = f(); c.alignment = Alignment(wrap_text=True, vertical='top')
    r0 = 5 + len(steps) + 1
    ws.cell(row=r0, column=1, value='Legend').font = f(True, size=12)
    c = ws.cell(row=r0 + 1, column=1, value='Yellow cell'); c.fill = INPUT_FILL; c.font = f(); c.border = BOX
    ws.cell(row=r0 + 1, column=2, value='Fill this in.').font = f()
    c = ws.cell(row=r0 + 2, column=1, value='EXAMPLE row'); c.fill = EX_FILL; c.font = f(italic=True, color=MUTED); c.border = BOX
    ws.cell(row=r0 + 2, column=2, value='Shows the expected format. It is ignored; overwrite or delete it.').font = f()
    c = ws.cell(row=r0 + 3, column=1, value='Red date'); c.fill = PatternFill('solid', fgColor='F9DCDA'); c.font = f(); c.border = BOX
    ws.cell(row=r0 + 3, column=2, value='End date is before the start date.').font = f()
    c = ws.cell(row=r0 + 4, column=1, value='Amber date'); c.fill = PatternFill('solid', fgColor='FBECCF'); c.font = f(); c.border = BOX
    ws.cell(row=r0 + 4, column=2, value='Not reviewed in over 30 days.').font = f()

    r1 = r0 + 6
    ws.cell(row=r1, column=1, value='Field guide').font = f(True, size=12)
    guide = [('Product area', 'Area code from the dropdown. Needed when one file holds several areas.', code or 'AZC'),
             ('ID', f'Unique ID: product area code + number, e.g. {code or "AZC"}-01. Never reuse or renumber an ID.', f'{code or "AZC"}-01'),
             ('Initiative', 'Short name a leader would recognize.', 'Kubernetes platform GA'),
             ('Strategic theme', 'Which enterprise theme it moves. See the Reference tab.', themes[0]['name'] if themes else ''),
             ('Horizon', 'Commit / Plan / Explore. See the Reference tab.', 'Commit'),
             ('Status', 'Delivery health right now.', 'On track'),
             ('Start / End date', 'Planned window. Move the end date if the plan changes, and say why in Risk note.', '9/1/2026'),
             ('Jira epic', 'Epic key only, not the URL.', 'PLAT-140'),
             ('Depends on', 'IDs this needs first, separated by semicolons. Can be another area\'s ID.', 'CLD-01; IAM-01'),
             ('Last reviewed', 'Date you last checked this row.', '10/7/2026'),
             ('Notes', 'Working notes, sources, assumptions. Not shown on the dashboard.', 'Dates assumed; confirm with PO')]
    for j, (k, v, ex) in enumerate(guide, r1 + 1):
        ws.cell(row=j, column=1, value=k).font = f(True)
        c = ws.cell(row=j, column=2, value=v); c.font = f(); c.alignment = Alignment(wrap_text=True, vertical='top')
        ws.cell(row=j, column=3, value=ex).font = f(color=MUTED)

    # About
    ab = wb.create_sheet('Product Area')
    ab.column_dimensions['A'].width = 26; ab.column_dimensions['B'].width = 36; ab.column_dimensions['C'].width = 50
    about = [('Product area code', code, 'Pick from the list. Leave blank in a combined file; use the Product area column instead.'),
             ('Product area name', (area or {}).get('name', ''), 'For reference only. The enterprise setup decides the official name.'),
             ('Updated by', updated_by, 'Your name.'),
             ('Last updated', dt.datetime.now() if example else None, 'Date you finished this update.')]
    for r, (k, v, note) in enumerate(about, 1):
        ab.cell(row=r, column=1, value=k).font = f(True)
        c = ab.cell(row=r, column=2, value=v); c.font = f(); c.fill = INPUT_FILL; c.border = BOX
        if k == 'Last updated': c.number_format = 'm/d/yyyy'
        ab.cell(row=r, column=3, value=note).font = f(color=MUTED)
    n_areas = max(len(areas), 1)
    dv_list(ab, f'=Reference!$M$2:$M${1 + n_areas}', 'B1')
    dv_date(ab, 'B4')

    # Initiatives
    it = wb.create_sheet('Initiatives')
    header(it, INIT_COLS)
    body(it, 2, ROWS + 1, len(INIT_COLS), date_cols=(7, 8, 14), wrap_cols=(3, 10, 13, 15))
    rows = list(initiatives)
    if example and not rows:
        rows = [{'id': f'EXAMPLE-01', 'title': 'Kubernetes platform GA', 'theme': themes[0]['id'] if themes else '', 'horizon': 'Commit',
                 'status': 'On track', 'start': '2026-09-01', 'end': '2027-04-30', 'owner': 'Jane Doe',
                 'summary': 'Shared Kubernetes with paved-road ingress and autoscaling.', 'jiraEpic': 'PLAT-140',
                 'dependsOn': ['CLD-01'], 'riskNote': '', 'lastReviewed': '2026-10-01', '_example': True}]
    tname = {t['id']: t['name'] for t in themes}
    for r, i in enumerate(rows, 2):
        vals = [i['id'], i.get('productArea') or code or None, i['title'], tname.get(i.get('theme'), i.get('theme', '')), i.get('horizon'), i.get('status'), d(i.get('start')),
                d(i.get('end')), i.get('owner'), i.get('summary'), i.get('jiraEpic'), '; '.join(i.get('dependsOn') or []),
                i.get('riskNote'), d(i.get('lastReviewed')), i.get('notes')]
        for c, v in enumerate(vals, 1):
            cell = it.cell(row=r, column=c, value=v or None)
            if i.get('_example'): cell.fill = EX_FILL; cell.font = f(italic=True, color=MUTED)
    for r in range(2 + len(rows), ROWS + 2):
        for c in range(1, len(INIT_COLS) + 1): it.cell(row=r, column=c).fill = INPUT_FILL
    last = ROWS + 1
    n_th = max(len(themes), 1)
    dv_list(it, f'=Reference!$M$2:$M${1 + max(len(areas), 1)}', f'B2:B{last}', 'Product area code. In a one-area file it matches the Product Area tab.', 'Product area')
    dv_list(it, f'=Reference!$B$2:$B${1 + n_th}', f'D2:D{last}', 'Which enterprise theme this moves.', 'Strategic theme')
    dv_list(it, '"Commit,Plan,Explore"', f'E2:E{last}', 'Commit = firm. Plan = indicative. Explore = options.', 'Horizon')
    dv_list(it, '"Not started,On track,At risk,Off track,Done"', f'F2:F{last}', 'At risk / Off track need a Risk note.', 'Status')
    dv_date(it, f'G2:H{last}'); dv_date(it, f'N2:N{last}')
    uniq = DataValidation(type='custom', formula1=f'COUNTIF($A$2:$A${last},A2)<=1', showErrorMessage=True,
                          errorTitle='Duplicate ID', error='This ID is already used. IDs must be unique.')
    it.add_data_validation(uniq); uniq.add(f'A2:A{last}')
    it.conditional_formatting.add(f'H2:H{last}', FormulaRule(formula=['AND($G2<>"",$H2<>"",$H2<$G2)'], fill=PatternFill('solid', fgColor='F9DCDA')))
    it.conditional_formatting.add(f'N2:N{last}', FormulaRule(formula=['AND($C2<>"",$N2<>"",TODAY()-$N2>30)'], fill=PatternFill('solid', fgColor='FBECCF')))
    it.conditional_formatting.add(f'M2:M{last}', FormulaRule(formula=['AND(OR($F2="At risk",$F2="Off track"),$M2="")'], fill=PatternFill('solid', fgColor='F9DCDA')))
    it.freeze_panes = 'D2'; it.auto_filter.ref = f'A1:{it.cell(row=1, column=len(INIT_COLS)).column_letter}{last}'

    # Milestones
    mt = wb.create_sheet('Milestones')
    header(mt, MS_COLS)
    body(mt, 2, ROWS + 1, len(MS_COLS), date_cols=(3,), wrap_cols=(2,))
    mrows = list(milestones)
    if example and not mrows:
        mrows = [{'initiative': 'EXAMPLE-01', 'title': 'Pilot with 2 teams', 'date': '2027-01-15', 'type': 'Pilot', 'done': False, '_example': True}]
    for r, m in enumerate(mrows, 2):
        for c, v in enumerate([m['initiative'], m['title'], d(m.get('date')), m.get('type'), 'Yes' if m.get('done') else 'No', m.get('jiraEpic')], 1):
            cell = mt.cell(row=r, column=c, value=v or None)
            if m.get('_example'): cell.fill = EX_FILL; cell.font = f(italic=True, color=MUTED)
    for r in range(2 + len(mrows), ROWS + 2):
        for c in range(1, len(MS_COLS) + 1): mt.cell(row=r, column=c).fill = INPUT_FILL
    dv_list(mt, f'=Initiatives!$A$2:$A${last}', f'A2:A{last}', 'Pick the initiative this milestone belongs to.', 'Initiative')
    dv_date(mt, f'C2:C{last}')
    dv_list(mt, '"Release,Pilot,Review gate,Decision"', f'D2:D{last}', 'Review gate = leadership checks outcome impact.', 'Type')
    dv_list(mt, '"Yes,No"', f'E2:E{last}')
    mt.freeze_panes = 'C2'

    # Reference
    rf = wb.create_sheet('Reference')
    blocks = [(1, [('Theme code', 11), ('Theme', 32), ('Description', 44)], [(t['id'], t['name'], t.get('description', '')) for t in themes]),
              (5, [('Horizon', 11), ('Meaning', 44)], HORIZONS),
              (8, [('Status', 12), ('Meaning', 48)], STATUSES),
              (11, [('Milestone type', 14)], [(t[0],) for t in TYPES]),
              (13, [('Area code', 10), ('Product area', 28)], [(a['id'], a['name']) for a in areas])]
    for col, cols, data in blocks:
        for k, (name, width) in enumerate(cols):
            cell = rf.cell(row=1, column=col + k, value=name)
            cell.font = f(True, 'FFFFFF'); cell.fill = HEAD_FILL; cell.border = BOX
            rf.column_dimensions[cell.column_letter].width = width
        for r, rowv in enumerate(data, 2):
            for k, v in enumerate(rowv):
                cell = rf.cell(row=r, column=col + k, value=v); cell.font = f(); cell.border = BOX
                cell.alignment = Alignment(wrap_text=True, vertical='top')
    rf.cell(row=len(themes) + 4, column=1, value='Themes and product areas come from the enterprise setup. Ask the Director to change them.').font = f(italic=True, color=MUTED)

    wb.active = 1 if code else 0
    wb.save(path)


def main():
    out = ROOT / 'templates'; out.mkdir(exist_ok=True)
    if len(sys.argv) > 1:
        settings, themes, areas = read_enterprise(sys.argv[1])
        make_product(out / 'Roadmap - TEMPLATE.xlsx', None, themes, areas, example=True)
        for a in areas:
            make_product(out / f"Roadmap - {a['id']}.xlsx", a, themes, areas, updated_by=a.get('deliveryManager', ''))
        print(f'Wrote blank roadmaps for {len(areas)} product areas to {out}')
        return
    sample = json.loads((ROOT / 'site' / 'data' / 'roadmap.sample.json').read_text())
    themes, areas = sample['themes'], sample['productAreas']
    make_enterprise(out / 'Enterprise Setup.xlsx', sample['settings'], themes, areas)
    make_product(out / 'Roadmap - TEMPLATE.xlsx', None, themes, areas, example=True)
    ex = ROOT / 'examples' / 'roadmaps'; ex.mkdir(parents=True, exist_ok=True)
    make_enterprise(ex / 'Enterprise Setup.xlsx', sample['settings'], themes, areas)
    for a in areas:
        inits = [i for i in sample['initiatives'] if i['productArea'] == a['id']]
        ids = {i['id'] for i in inits}
        make_product(ex / f"Roadmap - {a['id']}.xlsx", a, themes, areas, inits,
                     [m for m in sample['milestones'] if m['initiative'] in ids], updated_by=a.get('deliveryManager', ''))
    print(f'Wrote templates to {out} and examples to {ex}')


if __name__ == '__main__':
    main()
